
POST http://localhost:8000/graphql
content-type: application/json
X-REQUEST-TYPE: GraphQL

query{
  events{
    _id
    title
    date
    creator{
      email
      password
      createdEvents{
        price
        date
      }
    }
  }
}

###
POST http://localhost:3000/graphql
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjIxMzdiOTNkYTkyNzdhYzg3YTg2MGUiLCJlbWFpbCI6InVzZXIucGFzc0BnbWFpbC5jb20iLCJpYXQiOjE1OTYyMzcxMjYsImV4cCI6MTU5NjI0MDcyNn0.ChwlqAgknw8uA6XkrqSV9DtUyyBY9UhooLRll5xXG8o
X-REQUEST-TYPE: GraphQL

query {
  bookings{
    _id
    user{
      email
    }
    event{
      title
      date
    }
  }
}


###

POST http://localhost:3000/graphql
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjIxMzdiOTNkYTkyNzdhYzg3YTg2MGUiLCJlbWFpbCI6InVzZXIucGFzc0BnbWFpbC5jb20iLCJpYXQiOjE1OTYxOTM3ODcsImV4cCI6MTU5NjE5NzM4N30.bZlCKAC86RI20D-a1CfjfffywQo0ldsRI8LC_MeSMzE
X-REQUEST-TYPE: GraphQL

query {
  bookings{
    _id
    user{
      email
      createdEvents{
        price
      }
    }
    event{
      title
      date
    }
  }
}

###

POST http://localhost:3000/graphql
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjI3YzA3MTAyYTkzOTY2MDA5ZGM3YzciLCJlbWFpbCI6InRlc3RhYmNAZ21haWwuY29tIiwiaWF0IjoxNTk2NjE4NzgxLCJleHAiOjE1OTY2MjIzODF9.bPeU_GZzruzoMvxTewWCxYSq8-WSejn4avo54bxE9R0
X-REQUEST-TYPE: GraphQL

 mutation {
  createEvent(eventInput: {title: "test restruction", description: "test", price: 6.66, date: "2020-07-31T03:07:08.338Z"}) {
    title
    creator {
      email
      createdEvents {
        price
        date
      }
    }
  }
}

###
POST http://localhost:3000/graphql
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjIxMzdiOTNkYTkyNzdhYzg3YTg2MGUiLCJlbWFpbCI6InVzZXIucGFzc0BnbWFpbC5jb20iLCJpYXQiOjE1OTYxOTM3ODcsImV4cCI6MTU5NjE5NzM4N30.bZlCKAC86RI20D-a1CfjfffywQo0ldsRI8LC_MeSMzE
X-REQUEST-TYPE: GraphQL

query {
  login(userInput: {email:"user.pass@gmail.com", password:"1234"}){
    userId
    token
    tokenExpiration
  }
}

###
POST http://localhost:3000/graphql
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjI3YzA3MTAyYTkzOTY2MDA5ZGM3YzciLCJlbWFpbCI6InRlc3RhYmNAZ21haWwuY29tIiwiaWF0IjoxNTk2NjE4NzgxLCJleHAiOjE1OTY2MjIzODF9.bPeU_GZzruzoMvxTewWCxYSq8-WSejn4avo54bxE9R0
X-REQUEST-TYPE: GraphQL

mutation {
  cancelBooking(bookingId: "5f214deacf6db667ac018554") {
    title
  }
}

###
POST http://localhost:8000/graphql
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjI3YzA3MTAyYTkzOTY2MDA5ZGM3YzciLCJlbWFpbCI6InRlc3RhYmNAZ21haWwuY29tIiwiaWF0IjoxNTk2NjkzODUzLCJleHAiOjE1OTY2OTc0NTN9.AObGNMViPVmheYplYMR6-lvfmUVAu0TrXSticRKlc3E
X-REQUEST-TYPE: GraphQL

mutation {
  bookEvent(eventId:"5f214deacf6db667ac018554"){
    _id
    createdAt
    updatedAt
    event{
      title
      creator{
        email
        password
      }
    }
    user{
      email
      createdEvents{
        description
      }
    }
  }
}


###
POST http://localhost:8000/graphql
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjI3YzA3MTAyYTkzOTY2MDA5ZGM3YzciLCJlbWFpbCI6InRlc3RhYmNAZ21haWwuY29tIiwiaWF0IjoxNTk2NjkzODUzLCJleHAiOjE1OTY2OTc0NTN9.AObGNMViPVmheYplYMR6-lvfmUVAu0TrXSticRKlc3E
X-REQUEST-TYPE: GraphQL

 mutation {
  createEvent(eventInput: {title:"${title}", description:"${description}", price:9.99, date:"2020-07-31T03:07:08.338Z"}) {
    _id
    title
    description
    price
    date
    creator{
      _id
      email
    }
  }
}

###
POST http://localhost:8000/graphql
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjI3YzA3MTAyYTkzOTY2MDA5ZGM3YzciLCJlbWFpbCI6InRlc3RhYmNAZ21haWwuY29tIiwiaWF0IjoxNTk2NjkzODUzLCJleHAiOjE1OTY2OTc0NTN9.AObGNMViPVmheYplYMR6-lvfmUVAu0TrXSticRKlc3E
X-REQUEST-TYPE: GraphQL

query {
  events {
    _id
    title
    description
    price
    date
    creator{
      _id
      email
    }
  }
}

###
POST http://localhost:8000/graphql
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjI3YzA3MTAyYTkzOTY2MDA5ZGM3YzciLCJlbWFpbCI6InRlc3RhYmNAZ21haWwuY29tIiwiaWF0IjoxNTk2NjkzODUzLCJleHAiOjE1OTY2OTc0NTN9.AObGNMViPVmheYplYMR6-lvfmUVAu0TrXSticRKlc3E
X-REQUEST-TYPE: GraphQL

mutation {
  bookEvent(eventId:"5f214deacf6db667ac018554") {
    _id
    createdAt
    updatedAt
  }
}

###
POST http://localhost:8000/graphql
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjI3YzA3MTAyYTkzOTY2MDA5ZGM3YzciLCJlbWFpbCI6InRlc3RhYmNAZ21haWwuY29tIiwiaWF0IjoxNTk2NzA5OTU2LCJleHAiOjE1OTY3MTM1NTZ9.ifLbOJQnciyi2w4o8vilbE8Q1h-YmFm2TpgWsXb6lSw
X-REQUEST-TYPE: GraphQL

query {
  bookings {
    _id
    createdAt
    updatedAt
    user{
      email
    }
    event{
      _id
      title
      description
      date
    }
  }
}