
POST http://localhost:3000/graphql
content-type: application/json
X-REQUEST-TYPE: GraphQL

query{
  events{
    _id
    title
    date
    creator{
      email
      password
      createdEvents{
        price
        date
      }
    }
  }
}

###
POST http://localhost:3000/graphql
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjIxMzdiOTNkYTkyNzdhYzg3YTg2MGUiLCJlbWFpbCI6InVzZXIucGFzc0BnbWFpbC5jb20iLCJpYXQiOjE1OTYxOTM3ODcsImV4cCI6MTU5NjE5NzM4N30.bZlCKAC86RI20D-a1CfjfffywQo0ldsRI8LC_MeSMzE
X-REQUEST-TYPE: GraphQL

query {
  bookings{
    _id
    user{
      email
    }
    event{
      title
      date
    }
  }
}


###

POST http://localhost:3000/graphql
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjIxMzdiOTNkYTkyNzdhYzg3YTg2MGUiLCJlbWFpbCI6InVzZXIucGFzc0BnbWFpbC5jb20iLCJpYXQiOjE1OTYxOTM3ODcsImV4cCI6MTU5NjE5NzM4N30.bZlCKAC86RI20D-a1CfjfffywQo0ldsRI8LC_MeSMzE
X-REQUEST-TYPE: GraphQL

query {
  bookings{
    _id
    user{
      email
      createdEvents{
        price
      }
    }
    event{
      title
      date
    }
  }
}

###

POST http://localhost:3000/graphql
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjIxMzdiOTNkYTkyNzdhYzg3YTg2MGUiLCJlbWFpbCI6InVzZXIucGFzc0BnbWFpbC5jb20iLCJpYXQiOjE1OTYxOTM3ODcsImV4cCI6MTU5NjE5NzM4N30.bZlCKAC86RI20D-a1CfjfffywQo0ldsRI8LC_MeSMzE
X-REQUEST-TYPE: GraphQL

 mutation {
  createEvent(eventInput: {title: "test restruction", description: "test", price: 6.66, date: "2020-07-31T03:07:08.338Z"}) {
    title
    creator {
      email
      createdEvents {
        price
        date
      }
    }
  }
}

###
POST http://localhost:3000/graphql
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjIxMzdiOTNkYTkyNzdhYzg3YTg2MGUiLCJlbWFpbCI6InVzZXIucGFzc0BnbWFpbC5jb20iLCJpYXQiOjE1OTYxOTM3ODcsImV4cCI6MTU5NjE5NzM4N30.bZlCKAC86RI20D-a1CfjfffywQo0ldsRI8LC_MeSMzE
X-REQUEST-TYPE: GraphQL

query {
  login(userInput: {email:"user.pass@gmail.com", password:"1234"}){
    userId
    token
    tokenExpiration
  }
}

###
POST http://localhost:3000/graphql
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjIxMzdiOTNkYTkyNzdhYzg3YTg2MGUiLCJlbWFpbCI6InVzZXIucGFzc0BnbWFpbC5jb20iLCJpYXQiOjE1OTYxOTM3ODcsImV4cCI6MTU5NjE5NzM4N30.bZlCKAC86RI20D-a1CfjfffywQo0ldsRI8LC_MeSMzE
X-REQUEST-TYPE: GraphQL

mutation {
  cancelBooking(bookingId: "5f22aefbcb170225183c9a3f") {
    title
  }
}

###
POST http://localhost:3000/graphql
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjIxMzdiOTNkYTkyNzdhYzg3YTg2MGUiLCJlbWFpbCI6InVzZXIucGFzc0BnbWFpbC5jb20iLCJpYXQiOjE1OTYxOTM3ODcsImV4cCI6MTU5NjE5NzM4N30.bZlCKAC86RI20D-a1CfjfffywQo0ldsRI8LC_MeSMzE
X-REQUEST-TYPE: GraphQL

mutation {
  bookEvent(eventId:"5f215109989ca04c7c26caac"){
    event{
      title
      creator{
        email
        password
      }
    }
    user{
      email
      createdEvents{
        description
      }
    }
  }
}
